config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  post 'contacts/new' => 'contacts#create'
  get 'welcome/contact'
  get 'welcome/about'
  get 'welcome/services'
  get 'welcome/install'
  get 'welcome/maintenance'
  get 'welcome/lift'
  #post 'welcome/contact' => 'contacts#create', as: :contact
  root 'welcome#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

#def contact
  #ContactMailer.contact.deliver_now
  #flash[:alert] = "Thank you for contacting us."
  #redirect_to root_path
#end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, :raise => false

  #def new
    #@contact = Contact.new
  #end

  #def create
    #@contact = Contact.new(contact_params)

    #if @contact.save && @contact.nope.present?
      #flash.now[:notice] = 'You are a robot, you have no soul, but the soul of your creator is in jeopardy.  Repent and believe in Jesus Christ alone for salvation this very day.'
      #exit
    #else
      #ApplicationMailer.contact(@contact).deliver_now
      #flash.now[:notice] = 'Thank you for your message. We will contact you as soon as possible.'
      #flash.now[:error] = 'Cannot send message.'
    #end

    #redirect_to root_path
  #end

  #private

  #def contact_params
    #params.require(:contact).permit(:first_name, :last_name, :address, :phone, :email, :message, :referral, :nope)
  #end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def maintenance
  end

  def contact
  end

  def lift
  end

  def install
  end

  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlwaysOnTheLevel</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'jquery.mmenu.all', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'jquery' %>
    <%= javascript_include_tag 'jquery.mmenu.all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Coming+Soon|Montserrat|Amatic+SC|Raleway|Tinos" rel="stylesheet">
    <script src='https://www.google.com/recaptcha/api.js'></script>
  </head>
  <div class="navbar bmar0 bpad0">
    <div class="row">
      <div class="col-md-4 font2point5rem blackfont logofont pad25 lmar25 pull-left dispin posrel blackfont">
        <%= link_to(root_path, class: "nodec blackfont") do %>
          ALWAYS ON THE LEVEL<br />
          SEPTIC MAINTENANCE
        <% end %>
      </div>
      <div class="col-md-4 whitefont font4rem tmar20 tcent ralefont">
        <a class="navcallbtn whitefont nodec pad15 lpad25 rpad25 hvr-sweep-to-right" href="tel:2103786096"><span class="glyphicon glyphicon-earphone whitefont rmar15 nodec"></span><span class="whitefont nodec">210.378.6096</span></a>
      </div>
      <div class="col-md-4 pull-right tmar25 wid100per zplus1 rmar0 lmar0 lpad0 bmar0 bpad0">
        <a href="#menu" class="glyphicon glyphicon-menu-hamburger ccfont pull-right nodec posfx lmar90per tmar50 rmar0 rpad25" id="hamburger">
        </a>
        <nav id="menu" class="font2rem tcent ralefont z100 tmar150">
          <ul class="rmar25 tmar50 font2rem ralefont">
            <li class="hvr-glow pad25">
              <%= link_to "Home", root_path, class: "font2point5rem" %>
            </li>
            <li class="hvr-glow pad25">
              <%= link_to "Services", welcome_services_path, class: "font2point5rem" %>
            </li>
            <li class="hvr-glow pad25">
              <%= link_to "Septic Installation", welcome_install_path, class: "font2point5rem" %>
            </li>
            <li class="hvr-glow">
              <%= link_to "Aerobic Septic Maintenance", welcome_maintenance_path, class: "font2point5rem" %>
            </li>
            <li class="hvr-glow">
              <%= link_to "Lift Station Repairs", welcome_lift_path, class: "font2point5rem" %>
            </li>
            <li class="hvr-glow">
              <%= link_to "About Us", welcome_about_path, class: "font2point5rem" %>
            </li>
            <li>
              <%= link_to "Contact Us", welcome_contact_path, class: "font2point5rem" %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <body class="tmar0 tpad0">
    <%= yield %>
  </body>
  <%= render partial: 'welcome/map', locals: {welcome: @welcome } %>
</html>

app/views/welcome/_map.html.erb
<div class="tcent bmar25 tmar25 tpad0">
  <%= link_to "", root_path, class: "glyphicon glyphicon-home nodec ccfont" %>
</div>
<div class="ht150 zminus2 bmar0 bpad0">
  <div class="font3rem row blackback whitefont ralefont lpad50 tpad50 bpad50 zminus2 wid100per rmar0 rpad50 lmar0">
    <div class="col-md-8 dispin">Need Help? Contact Us:<br>
      <div class="font2rem whitefont ralefont tmar25 bmar10">Find out what we can do for you.
      </div>
    </div>
    <div class="col-md-4 rmar0 rpad0 tcent tmar0 tpad0 dispin">
      <%= link_to "Request a Quote", welcome_contact_path, class: "font2point5rem btn blackbutton hvr hvr-sweep-to-right pad15 lpad25 rpad25 tcent tmar15 dispin" %>
    </div>
  </div>
</div>
<div class="ht50 tealback tmar0 tpad0 bmar0 bpad0">
</div>
<div class="darkcyanback whitefont">
  <div class="row tpad50 bpad50">
    <div class="col-md-4 tcent bmar50">
      <div class="font2rem bline wid80per lmar10per bmar15">CONTACT US</div>
      <div class="font1point5rem lightgrayfont">Always on the Level<br> Septic Maintenance</div>
      <div>PO Box 993</div>
      <div>Boerne,TX 78006</div>
      <div style="color: white!important">(210)378-6096</div>
      <div>mikedunn.alwaysonthelevelseptic@gmail.com</div>
    </div>
    <div class="col-md-4 tcent bmar50">
      <div class="font2rem font2rem bline wid80per lmar10per bmar15">HOURS OF OPERATION</div>
      <div class="tcent dispin">
        <table class="tcent">
          <tr>
            <th>Monday</th>
            <th class="wid75"> </th>
            <th>7:00 am - 8:00 pm</th>
          </tr>
          <tr>
            <th>Tuesday</th>
            <th> </th>
            <th>7:00 am - 8:00 pm</th>
          </tr>
          <tr>
            <th>Wednesday</th>
            <th> </th>
            <th>7:00 am - 8:00 pm</th>
          </tr>
          <tr>
            <th>Thursday</th>
            <th> </th>
            <th>7:00 am - 8:00 pm</th>
          </tr>
          <tr>
            <th>Friday</th>
            <th> </th>
            <th>7:00 am - 8:00 pm</th>
          </tr>
          <tr>
            <th>Saturday</th>
            <th> </th>
            <th>9:00 am - 5:00 pm</th>
          </tr>
          <tr>
            <th>Sunday</th>
            <th> </th>
            <th>Closed answering phone only</th>
          </tr>
        </table>
      </div>
    </div>
    <div class="col-md-4 tcent bmar50">
      <div class="font2rem bline wid80per lmar10per bmar15">OUR SERVICES</div>
      <div class="font1point5rem lightgrayfont">Septic Installation<br> </div>
      <div>Aerobic Septic Maintenance</div>
      <div>Lift Station Repairs</div>
    </div>
    <div class="wid100per rmar0 rpad0 tcent tpad0 dispin tcent">
      <%= link_to "Appointments by Request", welcome_contact_path, class: "font2point5rem btn turqbutton hvr hvr-sweep-to-right1 pad15 lpad25 rpad25 tcent tmar15 dispin tcent" %>
    </div>
  </div>
</div>
<div class="turqback whitefont">
  <div class="font1point5rem grayfont tpad15 bpad15 tcent">©2018-2025 Always on the Level Septic Maintenance<br>All rights reserved |
      <%= link_to "Soli Deo Gloria", "https://www.sermonaudio.com/saplayer/playpopup.asp?SID=74091412491", class: "nodec grayfont", target: :_blank %>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="installback tpad75 bpad75 picshad">
  <div class="font5rem bldfnt whitefont ralefont tcent tpad75 bpad75 txtshadowblack">About Us
  </div>
</div>
<div class="row tpad50 bpad50 rpad50">
  <div class="col-md-8 tealfont pull-left ralefont font2rem bolder lmar30 bmar25">WE TAKE GREAT CARE IN SERVING OUR CUSTOMERS EXCEPTIONALLY<br><br>
    <div class="grayfont pull-left ralefont font2rem bolder bmar25">With over 21 years of experience in the septic industry, Always On The Level Septic Maintenance has the expertise to complete any septic task in a timely manner and with no over the top cost. Displaying artisan skill in efficient aerobic septic maintenance, lift station repair, and septic installation, owner Mike Dunn has excavated over 200 pools and installed over 300 septic systems.  He attributes the success of Always On the Level Excavating first to the goodness of God. His dedication to working hard, dealing honestly with everyone, and being willing to go ‘the extra mile’ has made him a household name that customers graciously recommend to their friends and neighbors. His success would not have been attainable without these recommendations and Mike is very grateful to them.<br><br>Always On The Level Septic Maintenance is family owned and believe in providing honest and trustworthy septic maintenance catered to your ultimate satisfaction. If you’re looking for tried and true septic maintenance with professional know-how within Kendall County, Comal County, Kerr County, and north side of Bexar County TX., contact us at 210-378-6096, we always pick up our phone!
    </div>
    <%= link_to "Contact Us", welcome_contact_path, class: "font2point5rem btn blackbutton hvr hvr-sweep-to-right pad15 lpad25 rpad25 tcent tmar35 bmar25 posrel tcent" %>
  </div>
  <div class="col-md-3 txtalignc img-responsive rmar0 rpad0">
    <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-concrete.jpg", class: "rpad0 tmar50 tpad0 picshad txtalignc lmar25" %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="wid100per lmar0 rmar0 lpad0 rpad0">
  <div class="heroback tpad75 bpad75 picshad">
    <div class="font4rem bldfnt whitefont ralefont tcent txtshadowblack">Welcome to Always on the Level Septic Maintenance
    </div>
    <div class="font2rem whitefont tcent tmar25">Kendall County, Comal County, Kerr County, and north side of Bexar County</div>
    <div class="tcent font2rem ralefont tmar50 whitefont">
    <%= link_to "See Our Services", welcome_services_path, class: "herobutton hvr-sweep-to-right nodec pad15 lpad25 rpad25 whitefont picshad" %>
    </div>
  </div>
  <div class="row tpad50 bpad50 bpad50 rpad50 lpad0">
    <div class="col-md-8 tealfont pull-left ralefont font2rem bolder lmar30 bmar25 lpad25">SPECIALIZING IN AEROBIC SEPTIC MAINTENANCE AND LIFT STATION REPAIRS<br><br>
      <div class="grayfont pull-left ralefont font2rem bolder bmar25">With 21 years of experience in the septic industry, Always On The Level Septic Maintenance, specializes in quality aerobic septic maintenance and lift station repair. Started in 2003, we are a family owned business that believes in providing personal and attentive customer service aimed at leaving you and your family completely satisfied. Never price gouging our clientele, we provide cost effective and trustworthy service that’s highly skilled and reliable. We actually answer the phone, and call you back right away.<br><br>For residents within Kendall County, Comal County, Kerr County, and north side of Bexar County, TX., call Mike Dunn at Always On The Level Septic Maintenance. We are always ready to answer your call.</div>
      <%= link_to "Learn More", welcome_about_path, class: "font2point5rem btn blackbutton hvr hvr-sweep-to-right pad15 lpad25 rpad25 tcent tmar35 bmar25 posrel tcent" %>
    </div>
    <div class="col-md-3 img-responsive tcent lmar20">
      <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-concrete.jpg", class: "rpad0 tmar0 tpad0 picshad tcent" %>
    </div>
  </div>
  <div class="row tpad50 bpad50 lmar0 rmar0 rpad0 whitesmokeground tcent">
    <div class="font3rem tealfont bolder tpad25 tcent lmar0 lpad0 rmar0 rpad0">SERVICES WE PROVIDE</div>
    <div class="tealline wid80per lmar10per bmar15"></div>
    <div class="row tcent">
      <div class="col-md-3 picshad bpad50 mar25 dispin tcent nofloat">
        <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-lift-system.jpg", class: "wid80per img-responsive tcent dispin tmar25 ht50per" %>
        <div class="tealfont font2point5rem tmar25 bline wid90per lmar5per">LIFT STATION<br>REPAIRS</div>
        <div class="grayfont font2rem tcent pad25">Septic lift stations use pumps and pipes used to increase your septic…</div>
        <div class="">
          <%= link_to "Read more", welcome_lift_path, class: "tealbutton whitefont hvr-sweep-to-right nodec pad15 lpad25 rpad25 whitefont picshad font2rem bolder" %>
        </div>
      </div>
      <div class="col-md-3 picshad bpad50 dispin mar25 tcent nofloat">
        <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-concrete-2jpg.jpg", class: "wid80per img-responsive tcent dispin tmar25 ht50per" %>
        <div class="tealfont font2point5rem tmar25 bline wid90per lmar5per">AEROBIC SEPTIC MAINTENANCE</div>
        <div class="grayfont font2rem tcent pad25">Aerobic treatment systems are an excellent way to increase water…</div>
        <div class="">
          <%= link_to "Read more", welcome_maintenance_path, class: "tealbutton whitefont hvr-sweep-to-right nodec pad15 lpad25 rpad25 whitefont picshad font2rem bolder" %>
        </div>
      </div>
      <div class="col-md-3 picshad bpad50 dispin mar25 tcent nofloat">
        <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-installation.jpg", class: "wid80per img-responsive tcent dispin tmar25 ht50per" %>
        <div class="tealfont font2point5rem tmar25 bline wid90per lmar5per">SEPTIC<br>INSTALLATION</div>
        <div class="grayfont font2rem tcent pad25">Septic installation is a lot more common in rural areas where houses are…</div>
        <div class="">
          <%= link_to "Read more", welcome_install_path, class: "tealbutton whitefont hvr-sweep-to-right nodec pad15 lpad25 rpad25 whitefont picshad font2rem bolder" %>
        </div>
      </div>
    </div>
  </div>
  <div class="specialblackback row picshad">
    <div class="tpad50 ralefont font3rem whitefont tcent bline wid80per lmar10per">AEROBIC SEPTIC MAINTENANCE
    </div>
    <div class="col-md-5 font2rem mar25 whitefont ralefont">Aerobic treatment systems are a marvelous way to recycle the usable water from your septic system and promote water efficiency. However, due to their complexity, these systems tend to require more maintenance and care. Aerobic treatment systems use forced air to create an aerobic environment that will treat wastewater, allowing it to be repurposed for used for surface irrigation.<br>At Always On The Level Septic Maintenance, we provide cost effective aerobic septic maintenance and repairs to keep your aerobic treatment system self-sufficient. We are a family owned company that offers trustworthy one-of-a-kind customer service that emphasizes your complete satisfaction.<br>Our aerobic septic maintenance includes:
      <ul class="tmar25 ralefont">
        <li>Soil analysis</li>
        <li>Septic permits</li>
        <li>Aerobic septic treatments</li>
        <li>Repairing, adjusting, or replacing any broken or malfunctioning parts</li>
        <li>Testing and recording the free chlorine residual</li>
        <li>Depth of sludge</li>
        <li>Volume of sludge</li>
        <li>Clarity tests</li>
        <li>And plenty more</li>
      </ul>
    </div>
    <div class="col-md-5 font2rem mar25 whitefont ralefont">
      If you’re looking for reliable aerobic septic maintenance within Kendall County, Comal County, Kerr County, and north side of Bexar County TX., contact us at 210-378-6096 today.<br><br>We service multiple aerobic treatment systems, including:
      <ul class="tmar25 ralefont">
        <li>Solar air</li>
        <li>Norweco</li>
        <li>Jet</li>
        <li>Bio Robix</li>
        <li>Bio Microbic</li>
        <li>Clear String</li>
        <li>New Water</li>
        <li>Aqua Save</li>
        <li>Aquaklear</li>
        <li>Cajun Air</li>
        <li>Hydro-Action</li>
      </ul>
      <%= link_to "Learn more", welcome_services_path, class: "tealbutton whitefont hvr-sweep-to-right nodec pad15 lpad25 rpad25 whitefont picshad font2rem bolder tmar50" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 tcent tmar75">
      <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-lift-system.jpg", class: "wid80per img-responsive tcent dispin tmar25 ht50per picshad tmar50" %>
      <a class="blackbutton2 nodec pad15 lpad50 rpad50 hvr-sweep-to-right picshad tmar50 bmar25" href="tel:2103786096"><span class="glyphicon glyphicon-earphone whitefont rmar15"></span><span class="whitefont">210.378.6096</span></a>
    </div>
    <div class="col-md-8 rpad25">
      <div class="font3rem tealfont tcent tpad50 bline">
        LIFT STATION REPAIRS
      </div>
      <div class="grayfont font2rem tpad25 lpad25">
        Lift stations are used to move wastewater from low to higher elevations when the the source is not satisfactory for gravity flow. Lift stations will also lower costly construction involved in lower excavation depths and piping.<br><br>At Always On The Level Septic Maintenance, we provide attentive, personal and quality lift station repairs and services that will have your system running at its best condition.<br><br>Included in our lift station repairs are:<br>
        <ul>
          <li>Non-clog lift stations</li>
          <li>Higher flow</li>
          <li>Wastewater receiving well</li>
          <li>Pumps and piping with associated valves</li>
          <li>Motors</li>
          <li>Power supply system</li>
          <li>Alarm system</li>
          <li>Odor control system</li>
          <li>And plenty more</li>
        </ul>
      </div>
    <div class="grayfont font2rem bpad50 lpad25">
      If you’re looking for all-inclusive and leading lift station repair within Kendall County, Comal County, Kerr County, and north side of Bexar County TX., contact us at 210-378-6096 and book your professional maintenance today.
    </div>
  </div>
</div>

app/views/welcome/install.html.erb
<div class="installback tpad75 bpad75 picshad">
  <div class="font5rem bldfnt whitefont ralefont tcent tpad75 bpad75 txtshadowblack">Septic Installation
  </div>
</div>
<div class="row tpad50 bpad50 rpad50">
  <div class="col-md-8 tealfont pull-left ralefont font2rem bolder lmar30 bmar25">SPECIALIZING IN AEROBIC SEPTIC MAINTENANCE AND LIFT STATION REPAIRS<br><br>
    <div class="grayfont pull-left ralefont font2rem bolder bmar25">Septic installation is a lot more common in rural areas where houses are commonly spaced far apart, creating difficulties in supplying centralized sewer systems. Also known as underground wastewater treatment systems, septic systems are watertight, simplistic, and ecological as they do not require miles of environmentally destructive piping. Septic tank maintenance is not enough. Depending on the level of usage and soil conditions, proper septic system installation is critical to ensure system has a long, useful life.<br><br>Available in Kendall County only, we are the #1 authority for septic installation. Our fully licensed and skillful team offers expert advice to guarantee your septic installment will endure the test of time and seasonal change. We are family owned and deliver dependable septic installation with top-notch customer service.<br><br>Included in our septic installations are:
      <ul>
        <li>Design and permitting</li>
        <li>Septic installation</li>
        <li>Control panel inspecting</li>
        <li>Tank pumping procedure</li>
        <li>Septic drainfield installation</li>
        <li>Septic tank risers</li>
        <li>And more</li>
      </ul>
    </div>
    <%= link_to "Contact Us", welcome_contact_path, class: "font2point5rem btn blackbutton hvr hvr-sweep-to-right pad15 lpad25 rpad25 tcent tmar35 bmar25 posrel tcent" %>
  </div>
  <div class="col-md-3 tcent img-responsive rmar0 rpad0">
    <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-concrete.jpg", class: "rpad0 tmar50 tpad0 picshad tcent lmar20" %>
  </div>
</div>

app/views/welcome/lift.html.erb
<div class="liftback tpad75 bpad75 picshad">
  <div class="font5rem bldfnt whitefont ralefont tcent tpad50 bpad75 txtshadowblack">Lift Station Repair
  </div>
</div>
<div class="row tpad50 bpad50 rpad50">
  <div class="col-md-8 tealfont pull-left ralefont font2rem bolder lmar30 bmar25">SPECIALIZING IN AEROBIC SEPTIC MAINTENANCE AND LIFT STATION REPAIRS<br><br>
    <div class="grayfont pull-left ralefont font2rem bolder bmar25">Septic lift stations use pumps and pipes used to increase your septic tanks’ wastewater elevation without the use of gravity. Their purpose is to pump water to a higher drain field than gravity flow would allow. This process results in much more reasonable maintenance due to the fact that the pipes are not as deep as traditional gravity conveyance septic tanks.<br><br>Always On The Level Septic Maintenance offers industry leading lift station repair at a cost-effective price. We take great pride in delivering optimal customer service, tailored to your exact needs, that will leave you and your family completely satisfied with our workmanship.<br><br>Our lift station repair includes:<br><br>
      <ul>
        <li>Unclogging</li>
        <li>Electrical boxes and switches</li>
        <li>Plumbing</li>
        <li>Pumps and motors</li>
        <li>Higher Flow</li>
        <li>Wastewater receiving well</li>
        <li>Pumps and piping with associated valves</li>
        <li>Equipment control</li>
        <li>Power supply system</li>
        <li>Alarm system</li>
        <li>Odor control system</li>
        <li>And more</li>
      </ul><br><br>
      If you’re in the market for expert lift station repair with amazingly attentive customer service, within Kendall County, Comal County, Kerr County, and north side of Bexar County TX., call us at 210-378-6096 today.
    </div>
    <%= link_to "Contact Us", welcome_contact_path, class: "font2point5rem btn blackbutton hvr hvr-sweep-to-right pad15 lpad25 rpad25 tcent tmar35 bmar25 posrel tcent" %>
  </div>
  <div class="col-md-3 txtalignc img-responsive rmar0 rpad0">
    <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-concrete.jpg", class: "rpad0 tmar50 tpad0 picshad txtalignc lmar15" %>
  </div>
</div>

app/views/welcome/services.html.erb
<div class="heroback tpad75 bpad75 picshad">
  <div class="font5rem bldfnt whitefont ralefont tcent tpad50 bpad75 txtshadowblack">Services
  </div>
</div>
<div class="row tpad25 bpad50 lmar0 rmar0 rpad0 whitesmokeground tcent">
  <div class="font3rem tealfont bolder tpad25 tcent lmar0 lpad0 rmar0 rpad0">SERVICES WE PROVIDE</div>
  <div class="tealline wid80per lmar10per bmar15"></div>
  <div class="row tcent">
    <div class="col-md-3 picshad bpad50 mar25 lmar30 dispin tcent nofloat">
      <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-lift-system.jpg", class: "wid80per img-responsive tcent dispin tmar25 ht50per" %>
      <div class="tealfont font2point5rem tmar25 bline wid90per lmar5per">LIFT STATION<br>REPAIRS</div>
      <div class="grayfont font2rem tcent pad25">Septic lift stations use pumps and pipes used to increase your septic…</div>
      <div class="">
        <%= link_to "Read more", welcome_lift_path, class: "tealbutton whitefont hvr-sweep-to-right nodec pad15 lpad25 rpad25 whitefont picshad font2rem bolder" %>
      </div>
    </div>
    <div class="col-md-3 picshad bpad50 dispin tcent nofloat mar25">
      <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-concrete-2jpg.jpg", class: "wid80per img-responsive tcent dispin tmar25 ht50per" %>
      <div class="tealfont font2point5rem tmar25 bline wid90per lmar5per">AEROBIC SEPTIC MAINTENANCE</div>
      <div class="grayfont font2rem tcent pad25">Aerobic treatment systems are an excellent way to increase water…</div>
      <div>
        <%= link_to "Read more", welcome_maintenance_path, class: "tealbutton whitefont hvr-sweep-to-right nodec pad15 lpad25 rpad25 picshad font2rem bolder" %>
      </div>
    </div>
    <div class="col-md-3 picshad bpad50 dispin tcent nofloat mar25">
      <%= image_tag "https://s3.us-east-2.amazonaws.com/always-on-the-level/septic-installation.jpg", class: "wid80per img-responsive tcent dispin tmar25 ht50per" %>
      <div class="tealfont font2point5rem tmar25 bline wid90per lmar5per">SEPTIC<br>INSTALLATION</div>
      <div class="grayfont font2rem tcent pad25">Septic installation is a lot more common in rural areas where houses are…</div>
      <div>
        <%= link_to "Read more", welcome_install_path, class: "tealbutton whitefont hvr-sweep-to-right nodec pad15 lpad25 rpad25 picshad font2rem bolder" %>
      </div>
    </div>
  </div>
  <div class="tmar25 bmar25">
    <%= link_to "Contact Us", welcome_contact_path, class: "blackbutton2 whitefont hvr-sweep-to-right nodec pad15 lpad50 rpad50 picshad font2rem bolder" %>
  </div>
</div>